[package]
name = "veloren-voxygen-anim"
version = "0.6.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Imbris <imbrisf@gmail.com>"]
edition = "2018"

[lib]
name = "voxygen_anim"
# Uncomment to use animation hot reloading
# Note: this breaks `cargo test`
#crate-type = ["lib", "cdylib"]

[features]
use-dyn-lib = ["libloading", "notify", "lazy_static", "log"]
be-dyn-lib = []

default = ["be-dyn-lib"]

[dependencies]
vek = { version = "0.11.2", features = ["serde"] }
common = { package = "veloren-common", path = "../../../common" }
libloading = { version = "0.6.2", optional = true }
notify = { version = "5.0.0-pre.2", optional = true }
lazy_static = { version = "1.4.0", optional = true }
log = { version = "0.4.8", optional = true }
