[workspace]
members = [
	"common",
	"client",
	"chat-cli",
	"server",
	"server-cli",
	"voxygen",
	"world",
	"worldsim",
]

[profile.dev]
opt-level = 2
overflow-checks = false

[profile.release]
debug = false
codegen-units = 1
lto = true
