[package]
name = "veloren-voxygen-egui"
version.workspace = true
edition.workspace = true
authors = ["Ben Wallis <atomyc@gmail.com>"]

[lints]
workspace = true

[features]
use-dyn-lib = ["common-dynlib"]
be-dyn-lib = []

[dependencies]
client = {package = "veloren-client", path = "../../client"}
common = {package = "veloren-common", path = "../../common"}
egui = "0.33"
egui_plot = "0.34"
egui-winit = "0.33"
lazy_static = { workspace = true }
winit = "0.30"
common-dynlib = {package = "veloren-common-dynlib", path = "../../common/dynlib", optional = true}
