[package]
authors = ["Ben Wallis <atomyc@gmail.com>"]
name = "veloren-voxygen-egui"
edition = "2018"
version = "0.9.0"

[features]
use-dyn-lib = ["voxygen-dynlib"]
be-dyn-lib = []

[dependencies]
client = {package = "veloren-client", path = "../../client"}
common = {package = "veloren-common", path = "../../common"}
egui = "0.15"
egui_winit_platform = "0.11"
lazy_static = "1.4.0"
voxygen-dynlib = {package = "veloren-voxygen-dynlib", path = "../dynlib", optional = true}


