[package]
name = "veloren-network-protocol"
description = "pure Protocol without any I/O itself"
version = "0.6.1"
authors = ["Marcel MÃ¤rtens <marcel.cochem@googlemail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
metrics = ["prometheus"]
trace_pedantic = [] # use for debug only

default = ["metrics"]

[dependencies]

#tracing and metrics
tracing = { version = "0.1", default-features = false }
prometheus = { version = "0.13", default-features = false, optional = true }
#stream flags
bitflags = "1.2.1"
rand = { version = "0.8" }
# async traits
async-trait = "0.1.42"
bytes = "^1"
hashbrown = { version = ">=0.12, <0.13" }

[dev-dependencies]
async-channel = "1.5.1"
tokio = { version = "1.14", default-features = false, features = ["rt", "macros"] }
criterion = { version = "0.3.4", features = ["default", "async_tokio"] }

[[bench]]
name = "protocols"
harness = false
