[package]
name = "veloren-world"
version = "0.8.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[features]
simd = ["vek/platform_intrinsics"]

default = ["simd"]

[dependencies]
common = { package = "veloren-common", path = "../common" }
common-net = { package = "veloren-common-net", path = "../common/net" }
bincode = "1.3.1"
bitvec = "0.20.1"
fxhash = "0.2.1"
image = { version = "0.23.12", default-features = false, features = ["png"] }
itertools = "0.10"
vek = { version = "0.12.0", features = ["serde"] }
noise = { version = "0.7", default-features = false }
num = "0.3.1"
ordered-float = "2.0.1"
hashbrown = { version = "0.9", features = ["rayon", "serde", "nightly"] }
lazy_static = "1.4.0"
tracing = { version = "0.1", default-features = false }
rand = "0.7"
rand_chacha = "0.2.1"
arr_macro = "0.1.2"
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
rayon = "1.5"
serde = { version = "1.0.110", features = ["derive"] }
ron = { version = "0.6", default-features = false }

[dev-dependencies]
criterion = "0.3"
tracing-subscriber = { version = "0.2.3", default-features = false, features = ["fmt", "chrono", "ansi", "smallvec"] }
minifb = "0.19.1"
