[package]
name = "veloren-world"
version = "0.3.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common" }
vek = "0.9.9"
noise = "0.5.1"
hashbrown = { version = "0.5.0", features = ["serde", "nightly"] }
lazy_static = "1.3.0"
rand = "0.7.0"
rand_chacha = "0.2.1"
zerocopy = "0.2.8"

[dev-dependencies]
minifb = { git = "https://github.com/emoon/rust_minifb.git" }
