[package]
name = "veloren-server-cli"
version = "0.4.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
server = { package = "veloren-server", path = "../server" }
common = { package = "veloren-common", path = "../common" }

heaptrack = "0.3.0"
log = "0.4.8"
pretty_env_logger = "0.3.0"
