[package]
name = "veloren-server-cli"
version = "0.4.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[features]
worldgen = ["server/worldgen"]
default = ["worldgen"]

[dependencies]
server = { package = "veloren-server", path = "../server", default-features = false }
common = { package = "veloren-common", path = "../common" }

log = "0.4.8"
pretty_env_logger = "0.3.1"
