[package]
name = "veloren-server-cli"
version = "0.8.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[features]
worldgen = ["server/worldgen"]
default = ["worldgen"]
tracy = ["common/tracy", "tracing-tracy"]
plugins = ["server/plugins"]

[dependencies]
server = { package = "veloren-server", path = "../server", default-features = false }
common = { package = "veloren-common", path = "../common" }
common-net = { package = "veloren-common-net", path = "../common/net" }

tokio = { version = "1", default-features = false, features = ["rt-multi-thread"] }
ansi-parser = "0.7"
clap = "2.33"
crossterm = "0.18"
lazy_static = "1"
signal-hook = "0.2.2"
termcolor = "1.1"
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.2.3", default-features = false, features = ["env-filter", "fmt", "chrono", "ansi", "smallvec"] }
ron = {version = "0.6", default-features = false}
serde = {version = "1.0", features = [ "rc", "derive" ]}

# Tracy
tracing-tracy = { version = "0.4.0", optional = true }

[dependencies.tui]
git = "https://github.com/fdehau/tui-rs.git"
branch="paragraph-scroll"
default-features = false
features = ['crossterm']
