version: "3.5"

services:
  game-server:
    image: registry.gitlab.com/veloren/veloren/server-cli:weekly
    stdin_open: true
    tty: true
    container_name: veloren-game-server-master
    ports:
      - "14004:14004"
      - "14005:14005"
    restart: on-failure:0
    volumes:
        - "./userdata:/opt/userdata"
    environment:
        - RUST_LOG=debug,common::net=info
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --stop-timeout 130s --cleanup veloren-game-server-master
    restart: on-failure:0
