version: "3.5"

services:
  game-server:
    image: registry.gitlab.com/veloren/veloren:master-server
    container_name: veloren-game-server-master
    ports:
      - "14004:14004"
      - "14005:14005"
    restart: on-failure:0
    volumes:
        - "./db:/opt/db"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup veloren-game-server-master