[package]
name = "veloren_network"
version = "0.1.0"
authors = ["Marcel MÃ¤rtens <marcel.cochem@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#serialisation
bincode = "1.2"
serde = { version = "1.0" }
#sending
crossbeam-channel = "0.4.2"
async-std = { version = "~1.5", default-features = false, features = ["std", "async-task", "default"] }
#tracing and metrics
tracing = { version = "0.1", default-features = false }
tracing-futures = "0.2"
prometheus = { version = "0.7", default-features = false }
#async
futures = { version = "0.3", features = ["thread-pool"] }
#mpsc channel registry
lazy_static = { version = "1.4", default-features = false }
rand = { version = "0.7" }

[dev-dependencies]
tracing-subscriber = { version = "0.2.3", default-features = false, features = ["env-filter", "fmt", "chrono", "ansi", "smallvec"] }
uvth = { version = ">= 3.0, <= 4.0", default-features = false }