[package]
name = "veloren_network"
version = "0.1.0"
authors = ["Marcel MÃ¤rtens <marcel.cochem@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#threadpool
uvth = "3.1"
#serialisation
bincode = "1.2"
serde = { version = "1.0", features = ["derive"] }
byteorder = "1.3"
#sending
async-std = { version = "1.5", features = ["std"] }
#tracing and metrics
tracing = "0.1"
tracing-futures = "0.2"
prometheus = "0.7"
#async
futures = { version = "0.3", features = ["thread-pool"] }
#mpsc channel registry
lazy_static = "1.4"
rand = "0.7"

[dev-dependencies]
tracing-subscriber = "0.2.3"