[package]
name = "veloren-voxygen-i18n-helpers"
version.workspace = true
description = "Crate for internalization and diagnostic of existing localizations."
edition.workspace = true
authors = ["juliancoffee <lightdarkdaughter@gmail.com>"]

[lints]
workspace = true

[dependencies]
common-net = {package = "veloren-common-net", path = "../../common/net"}
common = {package = "veloren-common", path = "../../common"}
i18n = {package = "veloren-client-i18n", path = "../../client/i18n"}
# Utility
tracing = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
vek = { workspace = true }
