[package]
name = "region"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]

[dependencies]
enum-map = "0.2.31"
rand = "0.5.0"
noise = "0.5.1"
nalgebra = "0.15.1"
coord = "0.9.1"
