[package]
authors = ["Imbris <imbrisf@gmail.com>"]
edition = "2018"
name = "veloren-voxygen-anim-dyn"
version = "0.10.0"

[lib]
# Using dylib instead of cdylib increases the size 3 -> 13 mb
# but it is needed to expose the symbols from the anim crate :(
# effect on compile time appears to be insignificant
crate-type = ["dylib"]

[features]
be-dyn-lib = ["veloren-voxygen-anim/be-dyn-lib"]

[dependencies]
veloren-voxygen-anim = { path = "../" }
