[package]
name = "common"
version = "0.1.0"
authors = ["Marcel MÃ¤rtens <marcel.cochem@googlemail.com>", "Terah <terah.dev@gmail.com>"]

[dependencies]
time = "0.1.40"
log = "0.4"
bincode = "1.0.0"
serde = "1.0.63"
serde_derive = "1.0.63"
get_if_addrs = "0.5.2"
nalgebra = { version= "0.15.1", features = ["serde-serialize"] }
byteorder = "1.2.3"
rand = "0.5.0"
lazy_static = "1.0.1"

[dependencies.coord]
version = "0.9.1"
features = ["serialize"]
