[package]
name = "veloren-common"
version = "0.2.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Maciej Ćwięka <mckol363@gmail.com>"]
edition = "2018"

[dependencies]
sphynx = { git = "https://gitlab.com/veloren/sphynx.git", features = ["serde1"], rev = "11cdc7422568aaabd376c87242a60f636e68b40d" }
specs-idvs = { git = "http://gitlab.nebulanet.cc/xacrimon/specs-idvs.git" }

specs = { version = "0.14.2", features = ["serde", "nightly"] }
vek = { version = "0.9.8", features = ["serde"] }
dot_vox = "4.0.0"
image = "0.22.0"
mio = "0.6.19"
mio-extras = "2.0.5"
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"
bincode = "1.1.4"
log = "0.4.8"
rand = "0.7.0"
rayon = "1.1.0"
lazy_static = "1.3.0"
lz4-compress = "0.1.1"
fxhash = "0.2.1"
find_folder = "0.3.0"
