[package]
name = "veloren-common"
version = "0.2.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Maciej Ćwięka <mckol363@gmail.com>"]
edition = "2018"

[dependencies]
sphynx = { git = "https://gitlab.com/veloren/sphynx.git", features = ["serde1"] }

specs = { version = "0.14", features = ["serde"] }
vek = { version = "0.9", features = ["serde"] }
dot_vox = "4.0"
image = "0.21"
mio = "0.6"
mio-extras = "2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.39"
bincode = "1.1"
log = "0.4"
rand = "0.6.5"
rayon = "1.0"
lazy_static = "1.3"
lz4-compress = "0.1"
fxhash = "0.2"
find_folder = "0.3"
