[package]
name = "veloren-common"
version = "0.5.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Maciej Ćwięka <mckol363@gmail.com>", "Imbris <imbrisf@gmail.com>"]
edition = "2018"

[features]
no-assets = []

[dependencies]
specs-idvs = { git = "https://gitlab.com/veloren/specs-idvs.git" }

specs = { version = "0.15.1", features = ["serde", "nightly", "storage-event-control"] }
vek = { version = "0.9.9", features = ["serde"] }
dot_vox = "4.0.0"
image = "0.22.3"
mio = "0.6.19"
mio-extras = "2.0.5"
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"
ron = "0.5.1"
bincode = "1.2.0"
log = "0.4.8"
rand = "0.7.2"
rayon = "^1.3.0"
lazy_static = "1.4.0"
lz4-compress = "0.1.1"
hashbrown = { version = "0.6.2", features = ["rayon", "serde", "nightly"] }
find_folder = "0.3.0"
parking_lot = "0.9.0"
crossbeam = "=0.7.2"
notify = "5.0.0-pre.1"
indexmap = "1.3.0"
sum_type = "0.2.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "chonk_benchmark"
harness = false

[[bench]]
name = "color_benchmark"
harness = false
