[package]
authors = ["juliancoffee <lightdarkdaughter@gmail.com>", "Marcel MÃ¤rtens <marcel.cochem@googlemail.com>"]
edition = "2018"
name = "veloren-common-assets"
description = "Crate for game loading assets for veloren."
version = "0.10.0"

[dependencies]
lazy_static = "1.4.0"
assets_manager = {version = "0.5.0", features = ["bincode", "ron", "json"]}
ron = { version = "0.6", default-features = false }
dot_vox = "4.0"
image = { version = "0.23.12", default-features = false, features = ["png"] }
tracing = "0.1"

# asset tweak
serde = {version = "1.0", features = ["derive"], optional = true}
serial_test = {version = "0.5", optional = true}

[dev-dependencies]
walkdir = "2.3.2"

[features]
hot-reloading = ["assets_manager/hot-reloading"]
asset_tweak = ["serial_test", "serde", "hot-reloading"]
