[package]
name = "async-recv"
version = "0.1.0"
authors = ["Marcel MÃ¤rtens <marcel.cochem@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uvth = "3.1"
network = { package = "veloren-network", path = "../../../network" }
clap = "2.33"
uuid = { version = "0.8", features = ["serde", "v4"] }
futures = "0.3"
tracing = "0.1"
chrono = "0.4"
tracing-subscriber = "0.2.0-alpha.4"
bincode = "1.2"
serde = "1.0"