[package]
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Imbris <imbrisf@gmail.com>"]
edition = "2021"
name = "veloren-voxygen-anim"
version = "0.10.0"

[features]
use-dyn-lib = ["lazy_static", "common-dynlib"]
be-dyn-lib = []
simd = ["vek/platform_intrinsics"]

default = ["simd"]

[dependencies]
common = {package = "veloren-common", path = "../../common"}
# inline_tweak = "1.0.2"
bytemuck = { version = "1.4", features=["derive"] }
vek = {version = "0.15.8", features = ["serde"]}
common-dynlib = {package = "veloren-common-dynlib", path = "../../common/dynlib", optional = true}

# Hot Reloading
lazy_static = {version = "1.4.0", optional = true}
