# Publishes veloren-server-cli to the GitLab container registry.
# https://gitlab.com/veloren/veloren/container_registry
docker:
  extends: .release
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags: ["veloren/veloren", "publish", "trusted"]
  dependencies:
    - linux-x86_64
  before_script:
    - ls "${CI_PROJECT_DIR}/server-cli/";
  script:
    # Help kaniko identify that it is running in a container.
    # Avoids this issue: https://github.com/GoogleContainerTools/kaniko/issues/1542
    - export container=docker;
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json;
    - |
      bash -lc '
        source "${CI_PROJECT_DIR}/.gitlab/scripts/util.sh";
        publishdockertag;
        if [ "${PUBLISH_DOCKER_TAG}"  != "" ]; then
          /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/server-cli/Dockerfile --destination "${CI_REGISTRY_IMAGE}/server-cli:${PUBLISH_DOCKER_TAG}";
        fi
      ';

gittag:
  stage: publish
  image:
    name: alpine/git:v2.49.1
    entrypoint: ["/bin/sh"]
  dependencies: []
  tags: ["veloren/veloren", "publish", "trusted"]
  before_script:
    - git --version;
    - git lfs --version;
  script:
    - git config --global user.email "gitlab-veloren-bot@veloren.net";
    - git config --global user.name "veloren-bot";
    - git config --global http.postBuffer 52428800;
    - git remote set-url origin https://veloren-bot:${GITLAB_TOKEN_WRITE}@${CI_PROJECT_URL:8};
    - |
      if [[ ! "${SCHEDULE_CADENCE}" =~ ${TAG_REGEX} ]]; then
        git reflog expire --expire=now --all;
        git gc --prune=now;
        git fetch;
        git tag -a "${SCHEDULE_CADENCE}" -m '' -f;
        git push origin "${SCHEDULE_CADENCE}" -f || echo "failed pushed, trying again" && sleep 5 && git status && git fsck && git push origin "${SCHEDULE_CADENCE}" -f;
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "schedule"

pages:
  stage: publish
  image: registry.gitlab.com/veloren/veloren-docker-ci/cache/quality:${CACHE_IMAGE_TAG}
  dependencies: []
  tags: ["veloren/veloren", "publish"]
  artifacts:
    paths:
      - public
    expire_in: 4 weeks
  script:
    - rm -rf public;
    - mkdir -p public;
    - RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo doc --no-deps --document-private-items;
    - mv target/doc/* public;
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"

gitlab_release:
  extends: .release
  stage: publish
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags: ["veloren/veloren", "publish", "trusted"]
  before_script:
    - echo "" # Override before_script in .gitlab-ci.yml
  dependencies:
    - linux-x86_64
    - linux-aarch64
    - macos-x86_64
    - macos-aarch64
    - windows-x86_64
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && ( $CI_COMMIT_TAG != null && $CI_COMMIT_TAG =~ $TAG_REGEX )
      when: on_success
  script:
    # These are exported by earlier jobs via reports/dotenv
    - echo "LINUX_X86_64_JOB_ID=$LINUX_X86_64_JOB_ID"
    - echo "LINUX_AARCH64_JOB_ID=$LINUX_AARCH64_JOB_ID"
    - echo "MACOS_X86_64_JOB_ID=$MACOS_X86_64_JOB_ID"
    - echo "MACOS_AARCH64_JOB_ID=$MACOS_AARCH64_JOB_ID"
    - echo "WINDOWS_X86_64_JOB_ID=$WINDOWS_X86_64_JOB_ID"
  release:
    name: "Veloren $CI_COMMIT_TAG"
    description: "Veloren release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: "Linux (aarch64)"
          link_type: "other"
          url: "https://gitlab.com/veloren/veloren/-/jobs/${LINUX_AARCH64_JOB_ID}/artifacts/download"
        - name: "Linux (x86_64)"
          link_type: "other"
          url: "https://gitlab.com/veloren/veloren/-/jobs/${LINUX_X86_64_JOB_ID}/artifacts/download"
        - name: "MacOS (aarch64)"
          link_type: "other"
          url: "https://gitlab.com/veloren/veloren/-/jobs/${MACOS_AARCH64_JOB_ID}/artifacts/download"
        - name: "MacOS (x86_64)"
          link_type: "other"
          url: "https://gitlab.com/veloren/veloren/-/jobs/${MACOS_X86_64_JOB_ID}/artifacts/download"
        - name: "Windows (x86_64)"
          link_type: "other"
          url: "https://gitlab.com/veloren/veloren/-/jobs/${WINDOWS_X86_64_JOB_ID}/artifacts/download"
