# Publishes veloren-server-cli to the gitlab container registry
# https://gitlab.com/veloren/veloren/container_registry
docker:
  stage: publish
  extends: .release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  dependencies:
    - linux
  before_script:
    - ls "$CI_PROJECT_DIR/server-cli/"
  tags:
    - veloren-docker
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/server-cli/Dockerfile --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-server"

pages:
  extends: .release
  stage: check-compile
  artifacts:
    paths:
    - public
  script:
    - rm -rf public
    - mkdir -p public
    - cargo doc --no-deps --all-features --document-private-items
    - mv target/doc/* public
